In [13]:
# INTRODUCTION to Matrices

In [14]:
import numpy as np
A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4],[-1, -2, 1]])
C = np.array([[-2, 1],[4, 1]])
D = np.array([[2],[6]])

print(B)

[[ 3  0  4]
 [-1 -2  1]]


In [15]:
print("Array B has",B.shape[0],"rows.")
print("Array B has",B.shape[1],"columns.")      

Array B has 2 rows.
Array B has 3 columns.


In [16]:
# The multiplication of a number and a matrix
print(3*A,'\n')

# The sum of two matrices of the same shape
print(A+C,'\n')

# The multiplication of two matrices
print(A@B)

[[3 9]
 [6 3]] 

[[-1  4]
 [ 6  2]] 

[[ 0 -6  7]
 [ 5 -2  9]]


In [17]:
# NumPy array objects have a method named transpose for this purpose
A = np.array([[5, 4, 0],[1, 8, 3],[6, 7, 2]])

## Note that the tranpose method must be called with (), the same as a function with no arguments.
A_T = A.transpose()

print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


In [18]:
# The NumPy function eye generates an identity matrix of the specified size. Note we only need to provide eye
# with one parameter since the identity matrix must be square. We show here the product of I with a random 5×5 matrix

I5 = np.eye(5)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# Matrix multiplication by columns

P = np.array([[1, 3, -2],[5, 2, 0],[4, 2, -1],[2, 2, 0]])
C = np.array([[0, 6, 2, 6],[-1, 1, -3, 4],[0, 2, 4, 8]])
X = C[0:3,2:3]
print(P,'\n')
print(C,'\n')
print(X,'\n')
print(P@X)

[[ 1  3 -2]
 [ 5  2  0]
 [ 4  2 -1]
 [ 2  2  0]] 

[[ 0  6  2  6]
 [-1  1 -3  4]
 [ 0  2  4  8]] 

[[ 2]
 [-3]
 [ 4]] 

[[-15]
 [  4]
 [ -2]
 [ -2]]


In [20]:
# LET'S TRY SOME EXCERCIES!

In [26]:
import numpy as np 

E = np.array([[5], [-2]])
F = np.array([[1, 6],[2, 0],[-1, -1]])
G = np.array([[2, 0],[-1, 3],[-1, 6]])
H = np.array([[3, 0, 1],[1, -2, 2],[3, 4, -1]])

print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(H)

[[ 5]
 [-2]]


[[ 1  6]
 [ 2  0]
 [-1 -1]]


[[ 2  0]
 [-1  3]
 [-1  6]]


[[ 3  0  1]
 [ 1 -2  2]
 [ 3  4 -1]]


In [ ]:
# Exercise 1: 

# Calculate −2E, G+F, 4F−G, HG, and GE using the following matrix definitions. Do the exercise on paper first, 
# then check by doing the calculation with NumPy arrays.

In [21]:
print(-2*E)

[[-10]
 [  4]]


In [27]:
print(G+F)

[[ 3  6]
 [ 1  3]
 [-2  5]]


In [28]:
print((4*F)-G)

[[  2  24]
 [  9  -3]
 [ -3 -10]]


In [29]:
print(H@G)

[[5 6]
 [2 6]
 [3 6]]


In [30]:
print(G@E)

[[ 10]
 [-11]
 [-17]]


In [33]:
# Exercise 2: Find the values of x and y so that this equation holds

A = np.array([[1, 3],[-4, 2]])
B = np.array([[3, None],[2, None]])
AB = np.array([[9, 10],[-8, 16]])

print(A)
print('\n')
print(B)
print('\n')
print(AB)

[[ 1  3]
 [-4  2]]


[['3' 'x']
 ['2' 'y']]


[[ 9 10]
 [-8 16]]


In [34]:
# Tworzymy układ równań wynikający z mnożenia macierzy A * B = AB
# Równania:
# 1 * x + 3 * y = 10
# -4 * x + 2 * y = 16

# Macierz współczynników
coeff_matrix = np.array([[1, 3], [-4, 2]])

# Wektor wyników
results = np.array([10, 16])

# Rozwiązanie układu równań
x_y = np.linalg.solve(coeff_matrix, results)

# Wyświetlenie wyników
x, y = x_y
print(f"x = {x}, y = {y}")

x = -2.0, y = 4.0
